SymblogBlogBundle_homepage:
    pattern: /
    defaults: { _controller: SymblogBlogBundle:Page:index }
    requirements:
        _method: GET
SymblogBlogBundle_about:
    pattern: /about
    defaults: { _controller: SymblogBlogBundle:Page:about }
    requirements: 
        _method: GET
SymblogBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: SymblogBlogBundle:Page:contact }
    requirements: 
        _method: GET        
